version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - onlyfy-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - onlyfy-network

  recommendation-service:
    image: recommendation-service:latest
    container_name: recommendation-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - onlyfy-network

  music-category-service:
    image: music-category-service:latest
    container_name: music-category-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - onlyfy-network

  search-service:
    image: search-service:latest
    container_name: search-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - onlyfy-network

networks:
  onlyfy-network:
    driver: bridge