spring.application.name=api-gateway
server.port=8080

# Conexión con el servidor Eureka (Usando el contenedor)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Configuración limpia de Rutas del API Gateway
spring.cloud.gateway.routes[0].id=music-category-route
spring.cloud.gateway.routes[0].uri=lb://music-category-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/categories/**

spring.cloud.gateway.routes[1].id=recommendation-route
spring.cloud.gateway.routes[1].uri=lb://recommendation-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/recommendations/**

spring.cloud.gateway.routes[2].id=search-route
spring.cloud.gateway.routes[2].uri=lb://search-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/search/**