# Nombre del microservicio
spring.application.name=recommendation-service

# Puerto en el que corre este servicio
server.port=8082

# Dirección del Servidor de Eureka para registrarse automáticamente
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuración opcional por si manejas base de datos en memoria (H2) para las pruebas
spring.datasource.url=jdbc:h2:mem:recommendationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true