spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Desactiva el modo de emergencia y obliga a Eureka a limpiar instancias muertas de inmediato
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000